package com.entreprise.transport.model;

import java.util.Objects;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * This class represents a vehicle in the system.
 * 
 * @author Ouagal Mahamat
 * @Entity indicates that this class is a JPA entity.
 * @Id indicates that this field is a primary key.
 * @GeneratedValue(strategy = GenerationType.IDENTITY) indicates that the
 * primary key is automatically generated by the database.
 */
@Entity
public class Vehicle {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;

	private String registrationNumber;
	private String status;
	private String model;

	/**
	 * Default constructor.
	 */
	public Vehicle() {
	}

	/**
	 * Gets the vehicle ID.
	 * @return the ID of the vehicle
	 */
	public int getId() {
		return id;
	}

	/**
	 * Sets the vehicle ID.
	 * @param id the new ID
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * Gets the registration number of the vehicle.
	 * @return the registration number
	 */
	public String getRegistrationNumber() {
		return registrationNumber;
	}

	/**
	 * Sets the registration number of the vehicle.
	 * @param registrationNumber the new registration number
	 */
	public void setRegistrationNumber(String registrationNumber) {
		this.registrationNumber = registrationNumber;
	}

	/**
	 * Gets the status of the vehicle.
	 * @return the status
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * Sets the status of the vehicle.
	 * @param status the new status
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * Gets the model of the vehicle.
	 * @return the model
	 */
	public String getModel() {
		return model;
	}

	/**
	 * Sets the model of the vehicle.
	 * @param model the new model
	 */
	public void setModel(String model) {
		this.model = model;
	}

	@Override
	public int hashCode() {
		return Objects.hash(id, model, registrationNumber, status);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Vehicle other = (Vehicle) obj;
		return id == other.id && Objects.equals(model, other.model)
				&& Objects.equals(registrationNumber, other.registrationNumber) && Objects.equals(status, other.status);
	}
}
